version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: kim-enterprise-db
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - kim-network
    restart: always

networks:
  kim-network:
    driver: bridge

volumes:
  mongodb_data:
